name: matrix build

on:
  push:
    branches:
      - main 

  pull_request:
    branches: [main]

jobs:
  new-job:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        pyton-version: ["3.9", "3.10"]
        os: ["windows","macos"]

    steps:
      - name: checkout the code
        uses: actions/checkout@v4
